[package]
name = "yawa"
version = "0.1.0"
edition = "2021"
authors = ["Yogesh Dhamija"]

[dependencies]
clap = { version = "*", features = ["derive"] }

[dev-dependencies]
assert_cmd = "*"
predicates = "2.0.3"
